### ISSUE TITLE
Github OAuth setup summary...

### ISSUE THREAD

**Issue by cgeyma** [gocd-contrib/gocd-oauth-login#46]
Trying to setup GoCD/Github OAuth.
After many tries, finally got it to work.

1. Set up a Github OAuth Application in Your Profile->Developer Settings->OAuth Application
2. Enter values in gocd-oauth-login plugin settings
Just need to fill in 
Server Base URL:* -> looks like it must just be the host (ex. https://abc.com and not https://abc.com/go
OAuth Client ID:* -> from step #1
OAuth Client Secret:* -> from step #2 
3. In GoCD Server, add an OAuth Client in the OAuth Clients tab
Name -> enter a name
OAuth Redirect URI - enter the value from Authorization callback URL from step #1

That above is the finally settings I have that works.
Go to GoCD login page, and click the Github icon.
It should bring you to the official Github login screen.
However, I believe if you are already logged into Github, it would bypass the Github login page.

Now, a few questions.
1. Would anyone with a Github login able to log into my GoCD server?
2. After logged in, the login user is "null". It shows in the upper right corner.

Thanks.

**Comment by varshavaradarajan** [comment]
@cgeyma , regarding your questions 
1. This is based on your gocd server configuration (/go/admin/config/server). If you want to allow any github user to login, then the checkbox for `Allow users that exist in LDAP, password file or via plugin to log into GoCD, even if they haven't been explicitly added to GoCD` must be checked (which it is by default).

2. This happens when the github display name is not set in the user's github profile. This is due to a bug in the json library that socialauth uses. We have upgraded the json dependency and will be releasing a new version of the plugin shortly.

**Comment by cgeyma** [comment]
Varsha, thanks very much for the helpful reply.
I am able to correct both on my side.


Patrick

**Comment by mynkow** [comment]
This must be in the readme. Without the @cgeyma steps it could take hours to do the setup.

**Comment by arvindsv** [comment]
@mynkow Please submit a PR for the README with the information you think is valuable. Thank you!

**Comment by rahulmr** [comment]
I am still facing issue with this. If my server base url is https://mydomain.eu what should be my Authorization callback url for github plugin.
Can someone please post a detailed description? I wanted to check what is the thing I am missing. I have added password file auth as well so do I need to remove that plugin?

**Comment by rahulmr** [comment]
This happens just posted comment and then got the solution. Thanks @varshavaradarajan 
I would just like to add here, after following the steps from @cgeyma , we need to go to user summary and add users if we have not checked the option mentioned by @varshavaradarajan to allow any user.
Just adding comments here so that it is helpful for me in future. I was almost struggling to get this fixed from a week just because of few silly things.
